In [1]:
import numpy as np

##create array using numpy
## create 1D array 283 187

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [8]:
## create 2D array
##attributes of NUmPy array

arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print("Shape: ",arr2.shape)
print("Number of dimensions: ", arr2.ndim)
print("size or the numb of elements: ",arr2.size)
print("Data type: ",arr2.dtype)
print("Item size (in bytes): ",arr2.itemsize)

Shape:  (2, 5)
Number of dimensions:  2
size or the numb of elements:  10
Data type:  int64
Item size (in bytes):  8


In [5]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#Numpy vectorized operations

arr3 = np.array([1,2,3,4,5])
arr4 = np.array([10,20,30,40,50])

## Element wise addition
print("Addition: ",arr3+arr4)

## Element wise substraction
print("Substractin: ",arr4-arr3)

## Element wise multilication
print("Multiplication: ",arr3*arr4)

## Element wise division
print("Division: ",arr4/arr3)

Addition:  [11 22 33 44 55]
Substractin:  [ 9 18 27 36 45]
Multiplication:  [ 10  40  90 160 250]
Division:  [10. 10. 10. 10. 10.]


In [10]:
#Universal fucntion

arr = np.array([2,3,4,5,6])

#sqare root
print(np.sqrt(arr))

#exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [12]:
## Array slicing and indexing

arr  = np.array([[1,2,3,4,5],[5,6,7,8,9],[9,10,11,12,13]])
print("Array: \n",arr)

Array: 
 [[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 9 10 11 12 13]]


In [21]:
arr[0,1]

np.int64(2)

In [20]:
# arr[1:,2:]
arr[0:2,3:]

array([[4, 5],
       [8, 9]])

In [22]:
arr[0,0]=100
print(arr)

[[100   2   3   4   5]
 [  5   6   7   8   9]
 [  9  10  11  12  13]]


In [23]:
arr[1:2,3:]=100
print(arr)

[[100   2   3   4   5]
 [  5   6   7 100 100]
 [  9  10  11  12  13]]


In [24]:
## statical concept -- Normalization
## to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

# calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalie the data
normalized_data = (data-mean)/std_dev
print("Normalized data: ",normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [25]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

# mean
print(np.mean(data))

#median 
print(np.median(data))

#standered deviation
std_dev = np.std(data)
print(std_dev)

#variance
print(np.var(data))


5.5
5.5
2.8722813232690143
8.25


In [29]:
## logical operations 

data = np.array([1,2,3,4,5,6,7,8,9,10])

data>5
#array([False, False, False, False, False,  True,  True,  True,  True,
        # True])

data[data>5]
# array([ 6,  7,  8,  9, 10])

data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])